// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { CountryWithBodiesDB } from '../countrywithbodies-db'
import { CountryWithBodiesService } from '../countrywithbodies.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-countrywithbodiesstable',
  templateUrl: './countrywithbodiess-table.component.html',
  styleUrls: ['./countrywithbodiess-table.component.css'],
})
export class CountryWithBodiessTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of CountryWithBodies instances
  selection: SelectionModel<CountryWithBodiesDB> = new (SelectionModel)
  initialSelection = new Array<CountryWithBodiesDB>()

  // the data source for the table
  countrywithbodiess: CountryWithBodiesDB[] = []
  matTableDataSource: MatTableDataSource<CountryWithBodiesDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.countrywithbodiess
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (countrywithbodiesDB: CountryWithBodiesDB, property: string) => {
      switch (property) {
        case 'ID':
          return countrywithbodiesDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return countrywithbodiesDB.Name;

        case 'NCols':
          return countrywithbodiesDB.NCols;

        case 'NRows':
          return countrywithbodiesDB.NRows;

        case 'XllCorner':
          return countrywithbodiesDB.XllCorner;

        case 'YllCorner':
          return countrywithbodiesDB.YllCorner;

        case 'NbBodies':
          return countrywithbodiesDB.NbBodies;

        case 'Step':
          return countrywithbodiesDB.Step;

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (countrywithbodiesDB: CountryWithBodiesDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the countrywithbodiesDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += countrywithbodiesDB.Name.toLowerCase()
      mergedContent += countrywithbodiesDB.NCols.toString()
      mergedContent += countrywithbodiesDB.NRows.toString()
      mergedContent += countrywithbodiesDB.XllCorner.toString()
      mergedContent += countrywithbodiesDB.YllCorner.toString()
      mergedContent += countrywithbodiesDB.NbBodies.toString()
      mergedContent += countrywithbodiesDB.Step.toString()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private countrywithbodiesService: CountryWithBodiesService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of countrywithbodies instances
    public dialogRef: MatDialogRef<CountryWithBodiessTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.countrywithbodiesService.CountryWithBodiesServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getCountryWithBodiess()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "NCols",
        "NRows",
        "XllCorner",
        "YllCorner",
        "NbBodies",
        "Step",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "NCols",
        "NRows",
        "XllCorner",
        "YllCorner",
        "NbBodies",
        "Step",
      ]
      this.selection = new SelectionModel<CountryWithBodiesDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getCountryWithBodiess()
    this.matTableDataSource = new MatTableDataSource(this.countrywithbodiess)
  }

  getCountryWithBodiess(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.countrywithbodiess = this.frontRepo.CountryWithBodiess_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let countrywithbodies of this.countrywithbodiess) {
            let ID = this.dialogData.ID
            let revPointer = countrywithbodies[this.dialogData.ReversePointer as keyof CountryWithBodiesDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(countrywithbodies)
            }
            this.selection = new SelectionModel<CountryWithBodiesDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, CountryWithBodiesDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as CountryWithBodiesDB[]
          for (let associationInstance of sourceField) {
            let countrywithbodies = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as CountryWithBodiesDB
            this.initialSelection.push(countrywithbodies)
          }

          this.selection = new SelectionModel<CountryWithBodiesDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.countrywithbodiess
      }
    )
  }

  // newCountryWithBodies initiate a new countrywithbodies
  // create a new CountryWithBodies objet
  newCountryWithBodies() {
  }

  deleteCountryWithBodies(countrywithbodiesID: number, countrywithbodies: CountryWithBodiesDB) {
    // list of countrywithbodiess is truncated of countrywithbodies before the delete
    this.countrywithbodiess = this.countrywithbodiess.filter(h => h !== countrywithbodies);

    this.countrywithbodiesService.deleteCountryWithBodies(countrywithbodiesID).subscribe(
      countrywithbodies => {
        this.countrywithbodiesService.CountryWithBodiesServiceChanged.next("delete")
      }
    );
  }

  editCountryWithBodies(countrywithbodiesID: number, countrywithbodies: CountryWithBodiesDB) {

  }

  // display countrywithbodies in router
  displayCountryWithBodiesInRouter(countrywithbodiesID: number) {
    this.router.navigate(["github_com_tenktenk_translate_go-" + "countrywithbodies-display", countrywithbodiesID])
  }

  // set editor outlet
  setEditorRouterOutlet(countrywithbodiesID: number) {
    this.router.navigate([{
      outlets: {
        github_com_tenktenk_translate_go_editor: ["github_com_tenktenk_translate_go-" + "countrywithbodies-detail", countrywithbodiesID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(countrywithbodiesID: number) {
    this.router.navigate([{
      outlets: {
        github_com_tenktenk_translate_go_presentation: ["github_com_tenktenk_translate_go-" + "countrywithbodies-presentation", countrywithbodiesID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.countrywithbodiess.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.countrywithbodiess.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<CountryWithBodiesDB>()

      // reset all initial selection of countrywithbodies that belong to countrywithbodies
      for (let countrywithbodies of this.initialSelection) {
        let index = countrywithbodies[this.dialogData.ReversePointer as keyof CountryWithBodiesDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(countrywithbodies)

      }

      // from selection, set countrywithbodies that belong to countrywithbodies
      for (let countrywithbodies of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = countrywithbodies[this.dialogData.ReversePointer as keyof CountryWithBodiesDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(countrywithbodies)
      }


      // update all countrywithbodies (only update selection & initial selection)
      for (let countrywithbodies of toUpdate) {
        this.countrywithbodiesService.updateCountryWithBodies(countrywithbodies)
          .subscribe(countrywithbodies => {
            this.countrywithbodiesService.CountryWithBodiesServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, CountryWithBodiesDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedCountryWithBodies = new Set<number>()
      for (let countrywithbodies of this.initialSelection) {
        if (this.selection.selected.includes(countrywithbodies)) {
          // console.log("countrywithbodies " + countrywithbodies.Name + " is still selected")
        } else {
          console.log("countrywithbodies " + countrywithbodies.Name + " has been unselected")
          unselectedCountryWithBodies.add(countrywithbodies.ID)
          console.log("is unselected " + unselectedCountryWithBodies.has(countrywithbodies.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let countrywithbodies = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as CountryWithBodiesDB
      if (unselectedCountryWithBodies.has(countrywithbodies.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<CountryWithBodiesDB>) = new Array<CountryWithBodiesDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          countrywithbodies => {
            if (!this.initialSelection.includes(countrywithbodies)) {
              // console.log("countrywithbodies " + countrywithbodies.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + countrywithbodies.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = countrywithbodies.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = countrywithbodies.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("countrywithbodies " + countrywithbodies.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<CountryWithBodiesDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
