// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { TranslationDB } from '../translation-db'
import { TranslationService } from '../translation.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-translation-sorting',
  templateUrl: './translation-sorting.component.html',
  styleUrls: ['./translation-sorting.component.css']
})
export class TranslationSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of Translation instances that are in the association
  associatedTranslations = new Array<TranslationDB>();

  constructor(
    private translationService: TranslationService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of translation instances
    public dialogRef: MatDialogRef<TranslationSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getTranslations()
  }

  getTranslations(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let translation of this.frontRepo.Translations_array) {
          let ID = this.dialogData.ID
          let revPointerID = translation[this.dialogData.ReversePointer as keyof TranslationDB] as unknown as NullInt64
          let revPointerID_Index = translation[this.dialogData.ReversePointer + "_Index" as keyof TranslationDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedTranslations.push(translation)
          }
        }

        // sort associated translation according to order
        this.associatedTranslations.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedTranslations, event.previousIndex, event.currentIndex);

    // set the order of Translation instances
    let index = 0

    for (let translation of this.associatedTranslations) {
      let revPointerID_Index = translation[this.dialogData.ReversePointer + "_Index" as keyof TranslationDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedTranslations.forEach(
      translation => {
        this.translationService.updateTranslation(translation)
          .subscribe(translation => {
            this.translationService.TranslationServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer +' done');
  }
}
