// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { CountryWithBodiesDB } from './countrywithbodies-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class CountryWithBodiesService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  CountryWithBodiesServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private countrywithbodiessUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.countrywithbodiessUrl = origin + '/api/github.com/tenktenk/translate/go/v1/countrywithbodiess';
  }

  /** GET countrywithbodiess from the server */
  getCountryWithBodiess(): Observable<CountryWithBodiesDB[]> {
    return this.http.get<CountryWithBodiesDB[]>(this.countrywithbodiessUrl)
      .pipe(
        tap(_ => this.log('fetched countrywithbodiess')),
        catchError(this.handleError<CountryWithBodiesDB[]>('getCountryWithBodiess', []))
      );
  }

  /** GET countrywithbodies by id. Will 404 if id not found */
  getCountryWithBodies(id: number): Observable<CountryWithBodiesDB> {
    const url = `${this.countrywithbodiessUrl}/${id}`;
    return this.http.get<CountryWithBodiesDB>(url).pipe(
      tap(_ => this.log(`fetched countrywithbodies id=${id}`)),
      catchError(this.handleError<CountryWithBodiesDB>(`getCountryWithBodies id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new countrywithbodies to the server */
  postCountryWithBodies(countrywithbodiesdb: CountryWithBodiesDB): Observable<CountryWithBodiesDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.post<CountryWithBodiesDB>(this.countrywithbodiessUrl, countrywithbodiesdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`posted countrywithbodiesdb id=${countrywithbodiesdb.ID}`)
      }),
      catchError(this.handleError<CountryWithBodiesDB>('postCountryWithBodies'))
    );
  }

  /** DELETE: delete the countrywithbodiesdb from the server */
  deleteCountryWithBodies(countrywithbodiesdb: CountryWithBodiesDB | number): Observable<CountryWithBodiesDB> {
    const id = typeof countrywithbodiesdb === 'number' ? countrywithbodiesdb : countrywithbodiesdb.ID;
    const url = `${this.countrywithbodiessUrl}/${id}`;

    return this.http.delete<CountryWithBodiesDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted countrywithbodiesdb id=${id}`)),
      catchError(this.handleError<CountryWithBodiesDB>('deleteCountryWithBodies'))
    );
  }

  /** PUT: update the countrywithbodiesdb on the server */
  updateCountryWithBodies(countrywithbodiesdb: CountryWithBodiesDB): Observable<CountryWithBodiesDB> {
    const id = typeof countrywithbodiesdb === 'number' ? countrywithbodiesdb : countrywithbodiesdb.ID;
    const url = `${this.countrywithbodiessUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.put<CountryWithBodiesDB>(url, countrywithbodiesdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated countrywithbodiesdb id=${countrywithbodiesdb.ID}`)
      }),
      catchError(this.handleError<CountryWithBodiesDB>('updateCountryWithBodies'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
