// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { CountrySpecDB } from './countryspec-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class CountrySpecService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  CountrySpecServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private countryspecsUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.countryspecsUrl = origin + '/api/github.com/tenktenk/translate/go/v1/countryspecs';
  }

  /** GET countryspecs from the server */
  getCountrySpecs(): Observable<CountrySpecDB[]> {
    return this.http.get<CountrySpecDB[]>(this.countryspecsUrl)
      .pipe(
        tap(_ => this.log('fetched countryspecs')),
        catchError(this.handleError<CountrySpecDB[]>('getCountrySpecs', []))
      );
  }

  /** GET countryspec by id. Will 404 if id not found */
  getCountrySpec(id: number): Observable<CountrySpecDB> {
    const url = `${this.countryspecsUrl}/${id}`;
    return this.http.get<CountrySpecDB>(url).pipe(
      tap(_ => this.log(`fetched countryspec id=${id}`)),
      catchError(this.handleError<CountrySpecDB>(`getCountrySpec id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new countryspec to the server */
  postCountrySpec(countryspecdb: CountrySpecDB): Observable<CountrySpecDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.post<CountrySpecDB>(this.countryspecsUrl, countryspecdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`posted countryspecdb id=${countryspecdb.ID}`)
      }),
      catchError(this.handleError<CountrySpecDB>('postCountrySpec'))
    );
  }

  /** DELETE: delete the countryspecdb from the server */
  deleteCountrySpec(countryspecdb: CountrySpecDB | number): Observable<CountrySpecDB> {
    const id = typeof countryspecdb === 'number' ? countryspecdb : countryspecdb.ID;
    const url = `${this.countryspecsUrl}/${id}`;

    return this.http.delete<CountrySpecDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted countryspecdb id=${id}`)),
      catchError(this.handleError<CountrySpecDB>('deleteCountrySpec'))
    );
  }

  /** PUT: update the countryspecdb on the server */
  updateCountrySpec(countryspecdb: CountrySpecDB): Observable<CountrySpecDB> {
    const id = typeof countryspecdb === 'number' ? countryspecdb : countryspecdb.ID;
    const url = `${this.countryspecsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.put<CountrySpecDB>(url, countryspecdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated countryspecdb id=${countryspecdb.ID}`)
      }),
      catchError(this.handleError<CountrySpecDB>('updateCountrySpec'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
