// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { PointDB } from './point-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class PointService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  PointServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private pointsUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.pointsUrl = origin + '/api/github.com/tenktenk/translate/go/v1/points';
  }

  /** GET points from the server */
  getPoints(): Observable<PointDB[]> {
    return this.http.get<PointDB[]>(this.pointsUrl)
      .pipe(
        tap(_ => this.log('fetched points')),
        catchError(this.handleError<PointDB[]>('getPoints', []))
      );
  }

  /** GET point by id. Will 404 if id not found */
  getPoint(id: number): Observable<PointDB> {
    const url = `${this.pointsUrl}/${id}`;
    return this.http.get<PointDB>(url).pipe(
      tap(_ => this.log(`fetched point id=${id}`)),
      catchError(this.handleError<PointDB>(`getPoint id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new point to the server */
  postPoint(pointdb: PointDB): Observable<PointDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.post<PointDB>(this.pointsUrl, pointdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`posted pointdb id=${pointdb.ID}`)
      }),
      catchError(this.handleError<PointDB>('postPoint'))
    );
  }

  /** DELETE: delete the pointdb from the server */
  deletePoint(pointdb: PointDB | number): Observable<PointDB> {
    const id = typeof pointdb === 'number' ? pointdb : pointdb.ID;
    const url = `${this.pointsUrl}/${id}`;

    return this.http.delete<PointDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted pointdb id=${id}`)),
      catchError(this.handleError<PointDB>('deletePoint'))
    );
  }

  /** PUT: update the pointdb on the server */
  updatePoint(pointdb: PointDB): Observable<PointDB> {
    const id = typeof pointdb === 'number' ? pointdb : pointdb.ID;
    const url = `${this.pointsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.put<PointDB>(url, pointdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated pointdb id=${pointdb.ID}`)
      }),
      catchError(this.handleError<PointDB>('updatePoint'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
