// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { TranslationDB } from './translation-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class TranslationService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  TranslationServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private translationsUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.translationsUrl = origin + '/api/github.com/tenktenk/translate/go/v1/translations';
  }

  /** GET translations from the server */
  getTranslations(): Observable<TranslationDB[]> {
    return this.http.get<TranslationDB[]>(this.translationsUrl)
      .pipe(
        tap(_ => this.log('fetched translations')),
        catchError(this.handleError<TranslationDB[]>('getTranslations', []))
      );
  }

  /** GET translation by id. Will 404 if id not found */
  getTranslation(id: number): Observable<TranslationDB> {
    const url = `${this.translationsUrl}/${id}`;
    return this.http.get<TranslationDB>(url).pipe(
      tap(_ => this.log(`fetched translation id=${id}`)),
      catchError(this.handleError<TranslationDB>(`getTranslation id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new translation to the server */
  postTranslation(translationdb: TranslationDB): Observable<TranslationDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.post<TranslationDB>(this.translationsUrl, translationdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`posted translationdb id=${translationdb.ID}`)
      }),
      catchError(this.handleError<TranslationDB>('postTranslation'))
    );
  }

  /** DELETE: delete the translationdb from the server */
  deleteTranslation(translationdb: TranslationDB | number): Observable<TranslationDB> {
    const id = typeof translationdb === 'number' ? translationdb : translationdb.ID;
    const url = `${this.translationsUrl}/${id}`;

    return this.http.delete<TranslationDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted translationdb id=${id}`)),
      catchError(this.handleError<TranslationDB>('deleteTranslation'))
    );
  }

  /** PUT: update the translationdb on the server */
  updateTranslation(translationdb: TranslationDB): Observable<TranslationDB> {
    const id = typeof translationdb === 'number' ? translationdb : translationdb.ID;
    const url = `${this.translationsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.put<TranslationDB>(url, translationdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated translationdb id=${translationdb.ID}`)
      }),
      catchError(this.handleError<TranslationDB>('updateTranslation'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
