// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { CountrySpecDB } from '../countryspec-db'
import { CountrySpecService } from '../countryspec.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-countryspecstable',
  templateUrl: './countryspecs-table.component.html',
  styleUrls: ['./countryspecs-table.component.css'],
})
export class CountrySpecsTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of CountrySpec instances
  selection: SelectionModel<CountrySpecDB> = new (SelectionModel)
  initialSelection = new Array<CountrySpecDB>()

  // the data source for the table
  countryspecs: CountrySpecDB[] = []
  matTableDataSource: MatTableDataSource<CountrySpecDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.countryspecs
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (countryspecDB: CountrySpecDB, property: string) => {
      switch (property) {
        case 'ID':
          return countryspecDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return countryspecDB.Name;

        case 'NbBodies':
          return countryspecDB.NbBodies;

        case 'Step':
          return countryspecDB.Step;

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (countryspecDB: CountrySpecDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the countryspecDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += countryspecDB.Name.toLowerCase()
      mergedContent += countryspecDB.NbBodies.toString()
      mergedContent += countryspecDB.Step.toString()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private countryspecService: CountrySpecService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of countryspec instances
    public dialogRef: MatDialogRef<CountrySpecsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.countryspecService.CountrySpecServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getCountrySpecs()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "NbBodies",
        "Step",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "NbBodies",
        "Step",
      ]
      this.selection = new SelectionModel<CountrySpecDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getCountrySpecs()
    this.matTableDataSource = new MatTableDataSource(this.countryspecs)
  }

  getCountrySpecs(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.countryspecs = this.frontRepo.CountrySpecs_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let countryspec of this.countryspecs) {
            let ID = this.dialogData.ID
            let revPointer = countryspec[this.dialogData.ReversePointer as keyof CountrySpecDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(countryspec)
            }
            this.selection = new SelectionModel<CountrySpecDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, CountrySpecDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as CountrySpecDB[]
          for (let associationInstance of sourceField) {
            let countryspec = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as CountrySpecDB
            this.initialSelection.push(countryspec)
          }

          this.selection = new SelectionModel<CountrySpecDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.countryspecs
      }
    )
  }

  // newCountrySpec initiate a new countryspec
  // create a new CountrySpec objet
  newCountrySpec() {
  }

  deleteCountrySpec(countryspecID: number, countryspec: CountrySpecDB) {
    // list of countryspecs is truncated of countryspec before the delete
    this.countryspecs = this.countryspecs.filter(h => h !== countryspec);

    this.countryspecService.deleteCountrySpec(countryspecID).subscribe(
      countryspec => {
        this.countryspecService.CountrySpecServiceChanged.next("delete")
      }
    );
  }

  editCountrySpec(countryspecID: number, countryspec: CountrySpecDB) {

  }

  // display countryspec in router
  displayCountrySpecInRouter(countryspecID: number) {
    this.router.navigate(["github_com_tenktenk_translate_go-" + "countryspec-display", countryspecID])
  }

  // set editor outlet
  setEditorRouterOutlet(countryspecID: number) {
    this.router.navigate([{
      outlets: {
        github_com_tenktenk_translate_go_editor: ["github_com_tenktenk_translate_go-" + "countryspec-detail", countryspecID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(countryspecID: number) {
    this.router.navigate([{
      outlets: {
        github_com_tenktenk_translate_go_presentation: ["github_com_tenktenk_translate_go-" + "countryspec-presentation", countryspecID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.countryspecs.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.countryspecs.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<CountrySpecDB>()

      // reset all initial selection of countryspec that belong to countryspec
      for (let countryspec of this.initialSelection) {
        let index = countryspec[this.dialogData.ReversePointer as keyof CountrySpecDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(countryspec)

      }

      // from selection, set countryspec that belong to countryspec
      for (let countryspec of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = countryspec[this.dialogData.ReversePointer as keyof CountrySpecDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(countryspec)
      }


      // update all countryspec (only update selection & initial selection)
      for (let countryspec of toUpdate) {
        this.countryspecService.updateCountrySpec(countryspec)
          .subscribe(countryspec => {
            this.countryspecService.CountrySpecServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, CountrySpecDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedCountrySpec = new Set<number>()
      for (let countryspec of this.initialSelection) {
        if (this.selection.selected.includes(countryspec)) {
          // console.log("countryspec " + countryspec.Name + " is still selected")
        } else {
          console.log("countryspec " + countryspec.Name + " has been unselected")
          unselectedCountrySpec.add(countryspec.ID)
          console.log("is unselected " + unselectedCountrySpec.has(countryspec.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let countryspec = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as CountrySpecDB
      if (unselectedCountrySpec.has(countryspec.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<CountrySpecDB>) = new Array<CountrySpecDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          countryspec => {
            if (!this.initialSelection.includes(countryspec)) {
              // console.log("countryspec " + countryspec.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + countryspec.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = countryspec.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = countryspec.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("countryspec " + countryspec.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<CountrySpecDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
