// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { TranslationDB } from '../translation-db'
import { TranslationService } from '../translation.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-translationstable',
  templateUrl: './translations-table.component.html',
  styleUrls: ['./translations-table.component.css'],
})
export class TranslationsTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of Translation instances
  selection: SelectionModel<TranslationDB> = new (SelectionModel)
  initialSelection = new Array<TranslationDB>()

  // the data source for the table
  translations: TranslationDB[] = []
  matTableDataSource: MatTableDataSource<TranslationDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.translations
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (translationDB: TranslationDB, property: string) => {
      switch (property) {
        case 'ID':
          return translationDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return translationDB.Name;

        case 'SourceCountryWithBodies':
          return (translationDB.SourceCountryWithBodies ? translationDB.SourceCountryWithBodies.Name : '');

        case 'TargetCountryWithBodies':
          return (translationDB.TargetCountryWithBodies ? translationDB.TargetCountryWithBodies.Name : '');

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (translationDB: TranslationDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the translationDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += translationDB.Name.toLowerCase()
      if (translationDB.SourceCountryWithBodies) {
        mergedContent += translationDB.SourceCountryWithBodies.Name.toLowerCase()
      }
      if (translationDB.TargetCountryWithBodies) {
        mergedContent += translationDB.TargetCountryWithBodies.Name.toLowerCase()
      }

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private translationService: TranslationService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of translation instances
    public dialogRef: MatDialogRef<TranslationsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.translationService.TranslationServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getTranslations()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "SourceCountryWithBodies",
        "TargetCountryWithBodies",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "SourceCountryWithBodies",
        "TargetCountryWithBodies",
      ]
      this.selection = new SelectionModel<TranslationDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getTranslations()
    this.matTableDataSource = new MatTableDataSource(this.translations)
  }

  getTranslations(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.translations = this.frontRepo.Translations_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let translation of this.translations) {
            let ID = this.dialogData.ID
            let revPointer = translation[this.dialogData.ReversePointer as keyof TranslationDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(translation)
            }
            this.selection = new SelectionModel<TranslationDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, TranslationDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as TranslationDB[]
          for (let associationInstance of sourceField) {
            let translation = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as TranslationDB
            this.initialSelection.push(translation)
          }

          this.selection = new SelectionModel<TranslationDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.translations
      }
    )
  }

  // newTranslation initiate a new translation
  // create a new Translation objet
  newTranslation() {
  }

  deleteTranslation(translationID: number, translation: TranslationDB) {
    // list of translations is truncated of translation before the delete
    this.translations = this.translations.filter(h => h !== translation);

    this.translationService.deleteTranslation(translationID).subscribe(
      translation => {
        this.translationService.TranslationServiceChanged.next("delete")
      }
    );
  }

  editTranslation(translationID: number, translation: TranslationDB) {

  }

  // display translation in router
  displayTranslationInRouter(translationID: number) {
    this.router.navigate(["github_com_tenktenk_translate_go-" + "translation-display", translationID])
  }

  // set editor outlet
  setEditorRouterOutlet(translationID: number) {
    this.router.navigate([{
      outlets: {
        github_com_tenktenk_translate_go_editor: ["github_com_tenktenk_translate_go-" + "translation-detail", translationID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(translationID: number) {
    this.router.navigate([{
      outlets: {
        github_com_tenktenk_translate_go_presentation: ["github_com_tenktenk_translate_go-" + "translation-presentation", translationID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.translations.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.translations.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<TranslationDB>()

      // reset all initial selection of translation that belong to translation
      for (let translation of this.initialSelection) {
        let index = translation[this.dialogData.ReversePointer as keyof TranslationDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(translation)

      }

      // from selection, set translation that belong to translation
      for (let translation of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = translation[this.dialogData.ReversePointer as keyof TranslationDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(translation)
      }


      // update all translation (only update selection & initial selection)
      for (let translation of toUpdate) {
        this.translationService.updateTranslation(translation)
          .subscribe(translation => {
            this.translationService.TranslationServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, TranslationDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedTranslation = new Set<number>()
      for (let translation of this.initialSelection) {
        if (this.selection.selected.includes(translation)) {
          // console.log("translation " + translation.Name + " is still selected")
        } else {
          console.log("translation " + translation.Name + " has been unselected")
          unselectedTranslation.add(translation.ID)
          console.log("is unselected " + unselectedTranslation.has(translation.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let translation = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as TranslationDB
      if (unselectedTranslation.has(translation.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<TranslationDB>) = new Array<TranslationDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          translation => {
            if (!this.initialSelection.includes(translation)) {
              // console.log("translation " + translation.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + translation.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = translation.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = translation.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("translation " + translation.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<TranslationDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
